name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        javaVersion: ["17"]
        mcVersion: ['1.16.5']
    name: Minecraft ${{ matrix.mcVersion }} with Java v${{ matrix.javaVersion }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.x
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: npm run start -- ${{ matrix.mcVersion }}
      - run: gradle run --args="--outputDir output"
